name: travel_minds
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

#----------------PACKAGES----------------#

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.19.0
  logger:
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  permission_handler: ^12.0.0+1
  carousel_slider: ^5.0.0
  translator: ^1.0.3+1
  flutter_tts: ^4.2.2
  firebase_auth: ^5.5.1  # or the latest version available
  firebase_core: ^3.12.1
  flutter_otp_text_field: ^1.5.1+1
  email_auth: ^2.0.0
  http: ^1.3.0
  bcrypt: ^1.1.3
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  animated_segmented_tab_control:
  razorpay_flutter:
#  flutter_vibrate: ^1.3.0
  open_file: ^3.5.10
  pdf:
  printing: ^5.14.2
  path_provider:
  dio:
  url_launcher: ^6.3.1
  http_parser: ^4.1.2
  lottie: ^3.3.1
  flutter_rating_bar: ^4.0.1
  webview_flutter: ^4.10.0
  provider: ^6.1.4

  # Icons
  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.8

  # State Management
  get_storage: ^2.1.1
  get: ^4.7.2
  sizer: ^3.0.5
  google_sign_in: ^6.3.0
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0



  # Product Specific
  mongo_dart: ^0.10.3
  device_preview:


#-------------------./ PACKAGES END -----------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  #------------------ LOCAL ASSETS -------------------#
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/images/flags/
    - assets/images/animation.json

  #------------------ LOCAL FONTS --------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 400
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600






  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
